### ISSUE TITLE
Were you able to see your IR LED through a camera?

### ISSUE THREAD

**Issue by christiancoleman** [PatrickSt1991/Roomba-VirtualWall-ESP32#1]
Sorry, this isn't an issue with the code necessarily, but I wanted to ask if you were able to see the IR LED when using an older camera without an IR filter. Also, was hoping to find out if it appeared to flash. I'm having trouble troubleshooting my own.

**Comment by PatrickSt1991** [comment]
Hi, I've never used a camera to try and visually see the IR been.

I'll try it and let you know, it isn't working at your end?

**Comment by PatrickSt1991** [comment]
> Sorry, this isn't an issue with the code necessarily, but I wanted to ask if you were able to see the IR LED when using an older camera without an IR filter. Also, was hoping to find out if it appeared to flash. I'm having trouble troubleshooting my own.

Hi, , I've never used a camera to try and visually see the IR been.
I'll try it and let you know, it isn't working at your end?

**Comment by christiancoleman** [comment]
Yeah unfortunately it's not working for me. Does yours show any light?

EDIT: I appreciate you taking my question btw.

**Comment by PatrickSt1991** [comment]
I've tried with my phone but it has the filter for IR, so I couldn't see it..

But what exactly isn't working? 
What version is your Roomba?

And did you use the IRremote library added with the ino file? cause if you use a different library it isn't working

**Comment by christiancoleman** [comment]
Ah interesting that you couldn't see it. Do you have an Android or an iPhone? I'm able to see my IR LEDs lit up in certain circumstances when I use my iPhone's front-facing camera. I have 840nm and 950nm IR LEDs and wasn't sure which one works. I think the 950s, but either way I'm trying them both. The 840nm IR LEDs can be seen with the naked eye, but the 950s require the front-facing camera. I think this only works with 950nm size?

> But what exactly isn't working?
> What version is your Roomba?

Well.. since I've been testing things based on whether or not I can see a shine in my phone I'm not sure I have been doing it correctly. If you put a regular LED in place of your IR LED would it light up too? I do indeed have the IRremote library. However, I'm just not sure I understand how things work when you have a numbered pin hooked up to the + voltage. What does that do? I couldn't get the IR LEDs to light when I had things hooked up that way. I had to hook the numbered pin to ground, and then in the code explicitly call out that I wanted to use the specific numbered pin.

I have the S9+. Here's a link: https://store.irobot.com/default/roomba-vacuuming-robot-vacuum-irobot-roomba-s9-plus/s955020.html

**Comment by PatrickSt1991** [comment]
I got a Android A70, I gues it can't see the IR.
This is the IR LED i'm using
https://www.tinytronics.nl/shop/nl/verlichting/led-los/ir-led-940nm-5mm-helder

You should hook up the postive leg of the IR to the 3.3v and the negative leg via a 220 ohm to any pin on the ESP32 (any pin on the ESP32 acts as a PWM pin)

And in the arduino file I declared pin 5 as the send pin.
int SEND_PIN = 5;
